// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./src/components/AppProvider/AppProvider.vue')['default']
    BasicForm: typeof import('./src/components/Form/components/BasicForm.vue')['default']
    BasicTable: typeof import('./src/components/Table/BasicTable.vue')['default']
    Breadcrumb: typeof import('./src/components/PageWrapper/Breadcrumb/Breadcrumb.vue')['default']
    Button: typeof import('./src/components/Button/Button.vue')['default']
    ColumnSetting: typeof import('./src/components/Table/components/ColumnSetting.vue')['default']
    Icon: typeof import('./src/components/Icon/Icon.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NElement: typeof import('naive-ui')['NElement']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    PageWrapper: typeof import('./src/components/PageWrapper/PageWrapper.vue')['default']
    Reload: typeof import('./src/components/Table/components/Reload.vue')['default']
    ResizeHeight: typeof import('./src/components/Table/components/ResizeHeight.vue')['default']
    SizeSetting: typeof import('./src/components/Table/components/SizeSetting.vue')['default']
    TableTools: typeof import('./src/components/Table/components/TableTools.vue')['default']
    ThemeTool: typeof import('./src/components/Application/Settings/ThemeTool.vue')['default']
  }
}

export { }
