// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./src/components/AppProvider/AppProvider.vue')['default']
    BasicForm: typeof import('./src/components/Form/components/BasicForm.vue')['default']
    BasicTable: typeof import('./src/components/Table/BasicTable.vue')['default']
    Breadcrumb: typeof import('./src/components/PageWrapper/Breadcrumb/Breadcrumb.vue')['default']
    Button: typeof import('./src/components/Button/Button.vue')['default']
    ColumnSetting: typeof import('./src/components/Table/components/ColumnSetting.vue')['default']
    Icon: typeof import('./src/components/Icon/Icon.vue')['default']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NElement: typeof import('naive-ui')['NElement']
    NForm: typeof import('naive-ui')['NForm']
    NFormItemGi: typeof import('naive-ui')['NFormItemGi']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NGrid: typeof import('naive-ui')['NGrid']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NPopover: typeof import('naive-ui')['NPopover']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NThemeEditor: typeof import('naive-ui')['NThemeEditor']
    NTooltip: typeof import('naive-ui')['NTooltip']
    PageWrapper: typeof import('./src/components/PageWrapper/PageWrapper.vue')['default']
    PButton: typeof import('./src/components/Button/PButton.vue')['default']
    Reload: typeof import('./src/components/Table/components/Reload.vue')['default']
    ResizeHeight: typeof import('./src/components/Table/components/ResizeHeight.vue')['default']
    SizeSetting: typeof import('./src/components/Table/components/SizeSetting.vue')['default']
    TableTools: typeof import('./src/components/Table/components/TableTools.vue')['default']
    ThemeTool: typeof import('./src/components/Application/Settings/ThemeTool.vue')['default']
  }
}

export { }
